spring:
  application:
    name: confession-form

  datasource:
    url: jdbc:mysql://localhost:3306/confession_form
    username: USERNAME
    password: PASSWORD

    hikari:
      maximum-pool-size: 10

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:

      ddl-auto: update
