spring:
  application:
    name: confession-form

  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/confession_form
    username: root
    password: ${DB_PASSWORD:}

    hikari:
      maximum-pool-size: 10

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:

      ddl-auto: update
